"""Build assets/gig-images/gig1/img-2.html from the REAL sample files (no hand-typed values).

Reads the raw rows from before_customers_messy.csv, the same customers from the cleaned
after_customers_clean.xlsx, and the headline numbers from its Validation Report sheet.
Run: python make_gig_image2.py   then   bash tools/render.sh assets/gig-images/gig1/img-2.html assets/gig-images/gig1/img-2.png
"""
import csv
import html
import os

import openpyxl

HERE = os.path.dirname(os.path.abspath(__file__))
SAMPLE = os.path.join(os.path.dirname(HERE), "01-customer-list")
OUT = os.path.join(HERE, "..", "..", "..", "assets", "gig-images", "gig1", "img-2.html")
PICK = [("nATHAN", "mcallister"), ("kofi", "MCALLISTER"), ("Declan", "TANAKA"), ("AMELIA", "everett")]

raw_rows = list(csv.reader(open(os.path.join(SAMPLE, "before_customers_messy.csv"), encoding="utf-8")))
hdr = raw_rows[2]
raw = [r for r in raw_rows[3:] if any(r)]
wb = openpyxl.load_workbook(os.path.join(SAMPLE, "after_customers_clean.xlsx"))
after = {r[0]: r for r in wb["Clean Data"].iter_rows(min_row=2, values_only=True)}
rep = {}
for r in wb["Validation Report"].iter_rows(values_only=True):
    if r[1] and r[2] is not None:
        rep[r[1]] = r[2]

picked = []
for first, last in PICK:
    r = next(x for x in raw if x[1].strip() == first and x[2].strip() == last)
    a = after[r[0]]
    picked.append((r, a))


def show_raw(s):
    # make stray spaces visible as-is (monospace, white-space: pre); NBSP shown as a space
    return html.escape(s.replace(" ", " "))


before_rows = "\n".join(
    f"<tr><td>{show_raw(r[1] + ',' + r[2])}</td><td>{show_raw(r[4])}</td><td>{show_raw(r[5])}</td>"
    f"<td class='num'>{show_raw(r[11])}</td></tr>" for r, a in picked)
after_rows = "\n".join(
    f"<tr><td>{html.escape(a[1] + ' ' + a[2])}</td><td>{html.escape(a[4])}</td><td>{a[5]:%Y-%m-%d}</td>"
    f"<td class='num'>${a[11]:,.2f}</td></tr>" for r, a in picked)
dups = rep["Exact duplicates removed"] + rep["Duplicates removed by Email"]
review = rep["Rows flagged for review"]

page = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Gig 1 image 2</title>
<!-- GENERATED by portfolio/gig1-data/_generator/make_gig_image2.py from the real sample files. Do not edit by hand. -->
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@500;600;700;800&family=JetBrains+Mono:wght@500&display=swap" rel="stylesheet">
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  html, body {{ width: 1280px; height: 769px; margin: 0; overflow: hidden; }}
  body {{ font-family: "Inter", "Segoe UI", Arial, sans-serif; color: #F8FAFC; position: relative;
    background: radial-gradient(900px 620px at 72% 50%, rgba(250,204,21,0.08), rgba(11,18,32,0) 60%),
                radial-gradient(700px 500px at 8% 12%, rgba(59,130,246,0.10), rgba(11,18,32,0) 60%), #0B1220; }}
  .left {{ position: absolute; left: 80px; top: 104px; width: 380px; }}
  h1 {{ font-weight: 800; font-size: 66px; line-height: 1.04; letter-spacing: -2px; }}
  h1 .accent {{ color: #FACC15; }}
  .sub {{ margin-top: 22px; font-size: 28px; line-height: 1.3; color: #94A3B8; font-weight: 500; }}
  ul {{ list-style: none; margin-top: 34px; }}
  li {{ font-size: 24px; font-weight: 600; margin-bottom: 16px; display: flex; gap: 12px; line-height: 1.25; }}
  li .ck {{ color: #34D399; font-weight: 800; }}
  .brand {{ position: absolute; left: 80px; bottom: 44px; font-size: 18px; font-weight: 500; color: #94A3B8; }}
  .right {{ position: absolute; right: 80px; top: 80px; width: 716px; }}
  .card {{ background: #131C2E; border: 1px solid rgba(148,163,184,0.18); border-radius: 18px; padding: 18px 20px 12px;
          box-shadow: 0 24px 60px rgba(0,0,0,0.35); }}
  .label {{ font-size: 15px; font-weight: 700; letter-spacing: 1.5px; text-transform: uppercase; color: #94A3B8; margin-bottom: 10px; }}
  .label b {{ color: #F8FAFC; }}
  table {{ width: 100%; border-collapse: collapse; }}
  th {{ text-align: left; background: #1F2A44; color: #F8FAFC; font-weight: 700; padding: 9px 8px; font-size: 15px; }}
  th.num, td.num {{ text-align: right; }}
  td {{ padding: 10px 8px; border-bottom: 1px solid rgba(148,163,184,0.14); font-size: 18px; font-weight: 500; white-space: nowrap; }}
  tr:last-child td {{ border-bottom: 0; }}
  .raw td {{ font-family: "JetBrains Mono", Consolas, monospace; font-size: 15px; color: #CBD5E1; white-space: pre; }}
  .clean td {{ font-variant-numeric: tabular-nums; }}
  .mid {{ text-align: center; font-size: 30px; color: #94A3B8; margin: 6px 0; line-height: 1; }}
  .src {{ margin-top: 12px; font-size: 14px; color: #94A3B8; text-align: right; }}
</style>
</head>
<body>
  <div class="left">
    <h1>Real before and <span class="accent">after</span></h1>
    <p class="sub">Sample customer export, {rep['Rows in']} rows in, {rep['Rows out']} clean out</p>
    <ul>
      <li><span class="ck">&#10003;</span><span>{dups} duplicates removed</span></li>
      <li><span class="ck">&#10003;</span><span>{rep['Cells changed']:,} cells fixed</span></li>
      <li><span class="ck">&#10003;</span><span>{review} rows flagged, not guessed</span></li>
    </ul>
  </div>
  <div class="right">
    <div class="card">
      <div class="label">Before &middot; <b>raw CSV export</b></div>
      <table class="raw">
        <tr><th>Name</th><th>Phone</th><th>Signup date</th><th class="num">Total spent</th></tr>
        {before_rows}
      </table>
    </div>
    <div class="mid">&darr;</div>
    <div class="card">
      <div class="label">After &middot; <b>Clean Data sheet</b></div>
      <table class="clean">
        <tr><th>Name</th><th>Phone</th><th>Signup date</th><th class="num">Total spent</th></tr>
        {after_rows}
      </table>
    </div>
    <div class="src">Same 4 customers, unedited rows from the portfolio sample (fictional data)</div>
  </div>
  <div class="brand">Garda &middot; AI-powered studio</div>
</body>
</html>
"""
with open(OUT, "w", encoding="utf-8") as f:
    f.write(page)
print("wrote", os.path.normpath(OUT))
